title: Vitruvian (CC0)
author: Hope, Olaf Delgado-Friedrichs
additional_authors: Hope (Shape,Morphs, Blendshapes, UVs, Textures, Rigging), Olaf Delgado-Friedrichs (Original Antonia Version, Topology), SirMaxim (Skin LUT), Upliner (Original Antonia Rigging), AgentA1CR (Node help.)
license: CC0

char_obj: cm_vitruvian
basis: Default
default_hair_length: 0.1
default_armature: rigify
default_texture_set: 4K

hair_library: hair.blend
hair_obj: hair-src
hairstyles:
    - Eve
    - Back1
    - Bob
    - Combover_zoro_d
    - SceneHair_1_O4saken
    - SlickedBack
    - mind_eyebrows_01
    - mind_eyebrows_02
    - mind_eyebrows_03
    - mind_eyebrows_04
    - mind_eyebrows_05
    - mind_eyebrows_06
    - mind_eyebrows_07
    - mind_eyebrows_08
    - mind_eyebrows_09
    - mind_eyebrows_10
    - mind_eyebrows_11_Default
    - mind_eyebrows_12
    - mind_eyebrows_13
    - mind_eyebrows_14
custom_morph_order: true
randomize_excl_regex: ^(Age|Fantasy).*$
recurse_materials: true

materials:
  - Iris
  - Mouth
  - Pupil
  - Sclera_Cornea
  - UDIM.Skin
  - charmorph_censor
  - EyeHair
  - Tearline
armature_defaults:
    type: rigify
    file: rigs.blend

armature:
   rigify:
    bones: bones.yaml
    ik_limits:
      MCH-forearm_ik.L:
        min: -10
        max: 140
      MCH-forearm_ik.R:
        min: -10
        max: 140
      MCH-shin_ik.L:
        min: -5
        max: 152
      MCH-shin_ik.R:
        min: -5
        max: 152
    title: Default (Modified Rigify)
    type: rigify
    file: rigs.blend
    obj_name: metarig
    drivers: drivers.json
    sliding_joints:
      elbows:
        upper_bone: upper_arm
        lower_bone: forearm
        side: [".L", ".R"]
        influence: 0.080
        verts_mul: [[7008, 20252], [2700, 25148], [6186, 20252], [1878, 25148]]
        verts_div: [[6186, 7039], [1878, 2731]]
        calc: (verts_mul/verts_div)**3*3.532

      knees:
        upper_bone: thigh
        lower_bone: shin
        side: [".L", ".R"]
        influence: 0.07
  
   mannequin:
    title: Unreal Mannequin (Experimental)
    type: regular
    file: rigs.blend
    obj_name: SK_UE5_Vitruvian
    weights: weights/mannequin.npz
    joints: joints/mannequin.npz
    
   mixamo:
    title: Mixamo (Game-Ready)
    type: regular
    file: rigs.blend
    obj_name: mixamo_vitruvian
    weights: weights/Mixamo.npz
    joints: joints/Mixamo.npz